CREATE TABLE IF NOT EXISTS guest_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hotel_name VARCHAR(255) NOT NULL,
    room_number VARCHAR(50) NOT NULL,
    guest_name VARCHAR(255),
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    booking_method VARCHAR(100) NOT NULL,
    booking_method_other VARCHAR(255),
    purpose_of_visit VARCHAR(100) NOT NULL,
    purpose_of_visit_other VARCHAR(255),
    cleanliness_room VARCHAR(20),
    cleanliness_bathroom VARCHAR(20),
    comfort_bed VARCHAR(20),
    room_facilities VARCHAR(20),
    bathroom_facilities VARCHAR(20),
    wifi VARCHAR(20),
    noise_levels VARCHAR(20),
    safety VARCHAR(20),
    staff_behavior VARCHAR(20),
    check_in_speed VARCHAR(20),
    maintenance VARCHAR(20),
    value_for_money VARCHAR(20),
    stay_again VARCHAR(10),
    recommend VARCHAR(10),
    like_most TEXT,
    improve TEXT,
    additional_comments TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
